nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: "@ftschirpke"
  description: a quantitative assessment of the underlying permafrost landscapes and,
    per extension, of the level of permafrost thaw in the region
  force: false
  is_nfcore: true
  name: troughgraph
  org: nf-core
  outdir: .
  version: 1.0dev
