bump_version: null
lint: null
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: "@ftschirpke"
  description: a quantitative assessment of the underlying permafrost landscapes and,
    per extension, of the level of permafrost thaw in the region
  force: false
  is_nfcore: true
  name: troughgraph
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
